import Head from 'next/head'
import Container from '@/components/Container'
import AboutUs from '@/components/AboutUs'
import WhyUs from '@/components/WhyUs'
import Team from '@/components/Team'
import Message from '@/components/Message'
import Social from '@/components/Social'
import Footer from '@/components/Footer'
import HorizontalContent from '@/components/HorizontalContent'
import OurVision from '@/components/OurVision'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <AboutUs />
        <OurVision />
        <WhyUs />
        <HorizontalContent />
        <Team />
        <Message />
        <Social />
        <Footer />
      </Container>
    </>
  )
}
